#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SudokuSolver.Droid.Resource", IsApplication=true)]

namespace SudokuSolver.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int layout_aspectRatio = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int layout_heightPercent = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int layout_marginBottomPercent = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int layout_marginEndPercent = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int layout_marginLeftPercent = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int layout_marginPercent = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int layout_marginRightPercent = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int layout_marginStartPercent = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int layout_marginTopPercent = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layout_widthPercent = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int button1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int button2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button3 = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int frameLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int numberPicker1 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NumPickPopUp = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PercentLayout_Layout = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
